[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile",
  "cd poll && pnpm install --frozen-lockfile",
  "cd ../syrian-contributors && pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "cd poll && pnpm run link:static && pnpm build",
  "cd ../syrian-contributors && pnpm build"
]

[start]
cmd = "node reverse-proxy.js"
